### ISSUE TITLE
to compile on bsd.

### ISSUE THREAD

**Issue by icepic** [mar77i/web77i#1]
diff --git a/global.mk b/global.mk
index b3230ac..a4fc2ab 100644
--- a/global.mk
+++ b/global.mk
@@ -16,7 +16,8 @@ VALGRIND_FLAGS = --leak-check=full --track-origins=yes --show-leak-kinds=all
 vg:
        valgrind $(VALGRIND_FLAGS) $(ARGS)
 
-DEV_CFLAGS = -Og -g
+DEV_CFLAGS = -g -O2
+#-Og -g
 PROD_CFLAGS = -O3
 PROD_LDFLAGS = -Wl,--discard-all
 
diff --git a/socket77i.h b/socket77i.h
index 66a7e23..b94c366 100644
--- a/socket77i.h
+++ b/socket77i.h
@@ -5,6 +5,7 @@
 #define SOCKET77I_H
 
 #include <stdbool.h>
+#include <sys/socket.h>
 
 #define BIND_RETRY_MAX 16
 #define HEADER_MAX 1024

**Comment by mar77i** [comment]
fixed by commit 9e75f0a
